Only allow admins to select different users for assignments
umts/screaming-dinosaur pull request #239
Opened 2022-11-18 20:35 UTC by bandogora

Closes #220

2022-11-21 17:18 UTC, bandogora commented
> Was the idea that we can't give other people our assignments, we can only take them from others?

That is correct, unless you are an admin in that roster.

2022-11-28 19:15 UTC, dirschn reviewed
It seems to me that you'd want to add more robust guards, specifically within the controller action to guard for this? I know that this is good _enough_ in most cases, but nothing is preventing someone from a little browser manipulation and then submitting the "wrong" user.

I know we are a standup group, but I still think frontend restrictions should be mirrored in the backend.

2022-11-28 20:27 UTC, bandogora commented
> It seems to me that you'd want to add more robust guards, specifically within the controller action to guard for this? I know that this is good _enough_ in most cases, but nothing is preventing someone from a little browser manipulation and then submitting the "wrong" user.

The gaurds are already in place:
https://github.com/umts/screaming-dinosaur/blob/a57901163f462e351a0f51b0a9c0f398d9f13d0e/app/controllers/assignments_controller.rb#L17
https://github.com/umts/screaming-dinosaur/blob/a57901163f462e351a0f51b0a9c0f398d9f13d0e/app/controllers/assignments_controller.rb#L80

2022-11-28 20:54 UTC, dirschn commented
Ah, I misunderstood what this PR was supposed to do. I get it now.

2023-01-25 18:18 UTC, werebus requested changes

2023-01-25 18:18 UTC, werebus commented on app/views/assignments/_form.html.haml
> +            class: 'form-control custom-select'
I don't think there's much point to a select box that will only ever have one option you can select

```suggestion
          = f.hidden_field :user_id, value: @current_user.id
          = f.text_field :user_name, value: @current_user.last_name, disabled: true, class: 'form-control'
```

2023-01-25 19:45 UTC, werebus approved these changes

2023-01-25 19:59 UTC, merged